import type { HomeData, Person, TipeDokumen } from "@/types/content";

export const fallbackHomeData: HomeData = {
  pageSetting: {
    logo: "sh-emblem.png",
    judul_hero: "PSHT SMKN DARUL ULUM MUNCAR",
    deskripsi_hero: "Suro Diro Jayaningrat Lebur Dening Pangastuti",
    gambar_hero: "foto-sekolah.webp",
    gambar_hero1: "foto-sekolah.png",
    gambar_hero2: "tentang.png",
    gambar_hero3: "people.png",
    judul_sejarah: "Sejarah Organisasi",
    deskripsi_sejarah: "Persaudaraan Setia Hati Terate menjadi ruang untuk membentuk pribadi yang berbudi luhur, tahu benar dan salah, serta menjaga persaudaraan di lingkungan SMKN Darul Ulum Muncar.",
    syarat_pendaftaran: `<h2><strong>Syarat Pendaftaran</strong></h2>
<ul>
<li><strong>Siswa Aktif - </strong>Terdaftar sebagai siswa aktif di sekolah.</li>
<li><strong>Usia Minimal -</strong>Minimal kelas VII (untuk SMP) atau kelas X (untuk SMA/SMK).</li>
<li><strong>Izin Orang Tua/Wali - </strong>Menyertakan surat izin dari orang tua atau wali.</li>
<li><strong>Kondisi Kesehatan - </strong>Sehat jasmani dan rohani, dibuktikan dengan surat keterangan sehat dari dokter (jika diperlukan).</li>
<li><strong>Komitmen Latihan - </strong>Bersedia mengikuti latihan secara rutin sesuai jadwal yang ditentukan.</li>
<li><strong>Perlengkapan Pribadi - </strong>Memiliki atau bersedia menyediakan perlengkapan latihan dasar (seragam silat, ikat pinggang, dll.).</li>
<li><strong>Tidak Terlibat Ekskul Bentrok- </strong>Tidak mengikuti kegiatan ekstrakurikuler lain yang memiliki jadwal bentrok dengan latihan silat.</li>
<li><strong>Bersedia Mengikuti Tata Tertib - </strong>Siap mengikuti aturan dan tata tertib yang berlaku dalam kegiatan ekstrakurikuler silat.</li>
</ul>
<p class="mt-8"><a href="https://docs.google.com/forms" target="_blank" rel="noopener noreferrer">Link Pendaftaran</a></p>`,
    gambar_sejarah: "tentang.png",
    gambar_sejarah1: "foto-sekolah.webp",
    gambar_sejarah2: null,
    gambar_sejarah3: null,
    visi: "Membentuk manusia berbudi luhur, tahu benar dan salah, serta beriman dan bertakwa kepada Tuhan Yang Maha Esa.",
    misi: "Membangun persaudaraan yang kuat dan menumbuhkan karakter disiplin, tangguh, serta peduli terhadap sesama.",
    judul_video: "Video Profil PSHT SMKNDU",
    deskripsi_video: "Saksikan perjalanan inspiratif kami dalam membangun organisasi yang menjunjung tinggi persatuan.",
    url_video: "https://www.youtube.com/embed/ii6jHl2Q_cQ",
    url_video1: "https://www.youtube.com/embed/LUUmBPsKMEA",
    url_video2: null,
    gambar_struktur_organisasi: null,
  },
  popularArticles: [
    {
      id: 1,
      slug: "manfaat-ekstrakurikuler-silat-untuk-siswa",
      judul: "Manfaat Ekstrakurikuler Silat untuk Siswa",
      isi: "<h2>Silat dan Disiplin</h2><p>Ekstrakurikuler silat di sekolah memberikan banyak manfaat bagi siswa. Selain melatih fisik, kegiatan ini juga membantu membentuk karakter yang disiplin dan tangguh. Siswa belajar menghormati pelatih dan teman melalui latihan yang terstruktur.</p><p>Silat juga melibatkan nilai-nilai budaya lokal yang penting untuk dilestarikan. Latihan silat dilakukan dengan tahapan-tahapan tertentu dan dipimpin oleh pelatih berpengalaman.</p><p>Dengan latihan rutin, siswa tidak hanya kuat secara fisik, tetapi juga mampu mengontrol emosi dan meningkatkan konsentrasi belajar di kelas.</p>",
      excerpt: "Silat dan Disiplin. Ekstrakurikuler silat di sekolah memberikan banyak manfaat bagi siswa. Selain melatih fisik, kegiatan ini juga membantu membentuk karakter yang disiplin dan tangguh.",
      legacy_user_id: 1,
      author_id: null,
      id_user: 1,
      kategori: "Umum",
      status: "published",
      published_at: "2025-05-30T00:15:13Z",
      view_count: 0,
      gambar: "artikel/01JWF35GWRCT9G82JCK1SM0JEE.jpg",
    },
    {
      id: 2,
      slug: "sejarah-dan-perkembangan-silat-di-sekolah",
      judul: "Sejarah dan Perkembangan Silat di Sekolah",
      isi: "<h2>Asal Usul Silat</h2><p>Silat merupakan seni bela diri tradisional yang sudah ada sejak ratusan tahun lalu. Di sekolah, silat menjadi salah satu ekstrakurikuler yang diminati karena mengandung unsur olahraga, seni, dan budaya.</p><p>Program ekstrakurikuler ini mulai diperkenalkan di sekolah-sekolah sejak tahun 1990-an, dan kini sudah menjadi bagian penting dalam pembinaan karakter siswa.</p><p>Dengan mengikuti silat, siswa juga diajak mengenal sejarah dan filosofi bela diri asli Indonesia, sehingga mereka lebih mencintai budaya bangsa.</p>",
      excerpt: "Asal Usul Silat. Silat merupakan seni bela diri tradisional yang sudah ada sejak ratusan tahun lalu. Di sekolah, silat menjadi salah satu ekstrakurikuler yang diminati.",
      legacy_user_id: 1,
      author_id: null,
      id_user: 1,
      kategori: "Umum",
      status: "published",
      published_at: "2025-05-30T00:10:00Z",
      view_count: 0,
      gambar: "artikel/01JWF3FF7S4QD6Y51XPV1BZRKK.jpg",
    },
    {
      id: 3,
      slug: "latihan-rutin-silat-apa-yang-dipelajari",
      judul: "Latihan Rutin Silat: Apa yang Dipelajari?",
      isi: "<h2>Teknik dan Materi Latihan</h2><p>Latihan silat dimulai dari pemanasan, penguasaan teknik dasar, hingga simulasi pertandingan. Siswa diajarkan berbagai jurus dasar, kuda-kuda, dan teknik pertahanan diri.</p><p>Setiap sesi latihan biasanya berlangsung 1 hingga 2 jam dan diakhiri dengan evaluasi. Selain itu, siswa juga diajarkan nilai-nilai sportivitas dan kerja sama tim.</p><p>Pelatih biasanya menyusun program latihan berdasarkan tingkatan dan kemampuan masing-masing siswa, sehingga proses belajar lebih efektif dan menyenangkan.</p>",
      excerpt: "Teknik dan Materi Latihan. Latihan silat dimulai dari pemanasan, penguasaan teknik dasar, hingga simulasi pertandingan. Siswa diajarkan berbagai jurus dasar dan kuda-kuda.",
      legacy_user_id: 1,
      author_id: null,
      id_user: 1,
      kategori: "Umum",
      status: "published",
      published_at: "2025-05-30T00:05:00Z",
      view_count: 0,
      gambar: "artikel/01JWF3DT7KV55VBX5PZKM5RRJP.jpg",
    },
    {
      id: 4,
      slug: "prestasi-tim-silat-sekolah-di-ajang-daerah",
      judul: "Prestasi Tim Silat Sekolah di Ajang Daerah",
      isi: "<h2>Raih Medali di Kejuaraan</h2><p>Tim silat dari sekolah kami telah mengikuti berbagai kejuaraan daerah dan nasional. Prestasi terbaru diraih dalam ajang Pencak Silat Pelajar tingkat kabupaten dengan membawa pulang 3 medali emas dan 1 perunggu.</p><p>Keberhasilan ini diraih berkat latihan yang konsisten, dukungan sekolah, serta semangat juang para siswa. Prestasi ini menjadi kebanggaan dan motivasi bagi siswa lain untuk ikut serta.</p><p>Silat bukan hanya soal bertarung, tetapi juga tentang kerja keras, fokus, dan semangat sportivitas yang tinggi.</p>",
      excerpt: "Raih Medali di Kejuaraan. Tim silat dari sekolah kami telah mengikuti berbagai kejuaraan daerah dan nasional dengan membawa pulang 3 medali emas dan 1 perunggu.",
      legacy_user_id: 1,
      author_id: null,
      id_user: 1,
      kategori: "ekstrakurikuler",
      status: "published",
      published_at: "2025-05-30T00:00:00Z",
      view_count: 0,
      gambar: "artikel/01JWF3CJNKB8NQAN8PTVW07G11.jpg",
    },
    {
      id: 5,
      slug: "mengapa-silat-cocok-untuk-semua-usia-sekolah",
      judul: "Mengapa Silat Cocok untuk Semua Usia Sekolah",
      isi: "<h2>Latihan yang Aman dan Bertahap</h2><p>Silat dirancang untuk semua kalangan usia, termasuk siswa SD hingga SMA. Program latihan disesuaikan dengan kemampuan dan usia peserta, sehingga aman untuk diikuti.</p><p>Siswa belajar dari gerakan sederhana terlebih dahulu sebelum mempelajari teknik lanjutan. Hal ini memungkinkan mereka beradaptasi dan menikmati setiap prosesnya.</p><p>Selain itu, latihan silat juga dapat membantu memperbaiki postur tubuh, meningkatkan kebugaran, dan mengurangi stres akibat aktivitas akademik yang padat.</p>",
      excerpt: "Latihan yang Aman dan Bertahap. Silat dirancang untuk semua kalangan usia, termasuk siswa SD hingga SMA. Program latihan disesuaikan dengan kemampuan dan usia peserta.",
      legacy_user_id: 1,
      author_id: null,
      id_user: 1,
      kategori: "ekstrakurikuler",
      status: "published",
      published_at: "2025-05-29T22:15:47Z",
      view_count: 0,
      gambar: "foto-sekolah.webp",
    },
    {
      id: 6,
      slug: "testimoni-siswa-tentang-ekstrakurikuler-silat",
      judul: "Testimoni Siswa tentang Ekstrakurikuler Silat",
      isi: "<h2>Pengalaman Pribadi</h2><p>\"Saya merasa lebih percaya diri setelah mengikuti silat. Selain tubuh menjadi lebih sehat, saya juga belajar mengendalikan emosi,\" ujar Andi, siswa kelas 10.</p><p>Banyak siswa merasakan manfaat positif dari mengikuti silat. Mereka menjadi lebih aktif, memiliki pertemanan yang sehat, dan termotivasi untuk meraih prestasi baik di akademik maupun non-akademik.</p><p>Dengan pembinaan yang tepat, ekstrakurikuler silat menjadi wadah yang ideal untuk pengembangan diri siswa secara menyeluruh.</p>",
      excerpt: "Pengalaman Pribadi. Banyak siswa merasakan manfaat positif dari mengikuti silat. Mereka menjadi lebih aktif, percaya diri, dan berprestasi.",
      legacy_user_id: 1,
      author_id: null,
      id_user: 1,
      kategori: "ekstrakurikuler",
      status: "published",
      published_at: "2025-05-29T22:00:00Z",
      view_count: 0,
      gambar: "tentang.png",
    },
  ],
  announcements: [
    {
      id: 1,
      judul: "Jadwal Latihan Rutin dan Persiapan Ujian Kenaikan Tingkat (UKT)",
      created_at: "2025-05-12T08:00:00Z",
      created_at_formatted: "12 Mei 2025",
      isi: "Diberitahukan kepada seluruh siswa PSHT SMKN Darul Ulum Muncar bahwa latihan rutin dilaksanakan setiap hari Selasa dan Jumat pukul 15.30 WIB di Lapangan Utama Sekolah. Seluruh siswa diharapkan hadir tepat waktu dengan mengenakan pakaian sakral lengkap dan membawa kelengkapan latihan masing-masing untuk persiapan evaluasi materi teknik dan fisik.",
      lampiran: "pengumuman/01JVMHP3HKNR4RF93RFQQAZKCN.pdf",
      attachments: [
        {
          id: 101,
          pengumuman_id: 1,
          label: "Surat Edaran UKT dan Jadwal Resmi",
          asset_type: "document",
          resource_type: "raw",
          secure_url: "pengumuman/01JVMHP3HKNR4RF93RFQQAZKCN.pdf",
          public_id: "psht/pengumuman/01JVMHP3HKNR4RF93RFQQAZKCN",
          format: "pdf",
          mime_type: "application/pdf",
          bytes: 134774,
          sort_order: 1,
        },
        {
          id: 102,
          pengumuman_id: 1,
          label: "Bagan Alur Lokasi Ujian di Lapangan",
          asset_type: "image",
          resource_type: "image",
          secure_url: "foto-sekolah.webp",
          public_id: "psht/pengumuman/foto-sekolah",
          format: "webp",
          mime_type: "image/webp",
          bytes: 164030,
          sort_order: 2,
        },
      ],
    },
    {
      id: 2,
      judul: "Pendaftaran Calon Siswa Baru Ekstrakurikuler PSHT Tahun Ajaran 2025/2026",
      created_at: "2025-05-05T09:00:00Z",
      created_at_formatted: "05 Mei 2025",
      isi: "Pendaftaran anggota baru ekstrakurikuler Persaudaraan Setia Hati Terate Rayon SMKN Darul Ulum Muncar telah resmi dibuka. Kegiatan ini terbuka bagi seluruh siswa-siswi yang memiliki tekad untuk belajar seni bela diri pencak silat, melatih kedisiplinan mental, dan menumbuhkan budi pekerti luhur. Formulir pendaftaran dapat diambil di sekretariat OSIS atau melalui perwakilan pengurus rayon.",
      lampiran: "pengumuman/01JWF4FV33HE9VA7XKXSGZRMN0.pdf",
      attachments: [
        {
          id: 201,
          pengumuman_id: 2,
          label: "Formulir Pendaftaran Siswa Baru",
          asset_type: "document",
          resource_type: "raw",
          secure_url: "pengumuman/01JWF4FV33HE9VA7XKXSGZRMN0.pdf",
          public_id: "psht/pengumuman/01JWF4FV33HE9VA7XKXSGZRMN0",
          format: "pdf",
          mime_type: "application/pdf",
          bytes: 25534,
          sort_order: 1,
        },
        {
          id: 202,
          pengumuman_id: 2,
          label: "Poster Informasi Ekstrakurikuler",
          asset_type: "image",
          resource_type: "image",
          secure_url: "tentang.png",
          public_id: "psht/pengumuman/tentang",
          format: "png",
          mime_type: "image/png",
          bytes: 300080,
          sort_order: 2,
        },
      ],
    },
    {
      id: 3,
      judul: "Kegiatan Bakti Sosial dan Silaturahmi Warga di Lingkungan Sekolah",
      created_at: "2025-04-25T07:30:00Z",
      created_at_formatted: "25 April 2025",
      isi: "Dalam rangka mempererat tali persaudaraan dan kepedulian terhadap lingkungan sekitar, PSHT Rayon SMKN Darul Ulum Muncar akan mengadakan agenda bakti sosial gotong royong bersama warga dan siswa. Seluruh anggota diharapkan berpartisipasi aktif dalam kegiatan sosial ini sebagai wujud nyata pengamalan falsafah Memayu Hayuning Bawana.",
      lampiran: null,
      attachments: [
        {
          id: 301,
          pengumuman_id: 3,
          label: "Foto Dokumentasi Kegiatan Bakti Sosial",
          asset_type: "image",
          resource_type: "image",
          secure_url: "01JJTRV90P9JSQ5HTF5AC36M36.jpg",
          public_id: "psht/pengumuman/01JJTRV90P9JSQ5HTF5AC36M36",
          format: "jpg",
          mime_type: "image/jpeg",
          bytes: 430221,
          sort_order: 1,
        },
      ],
    },
    {
      id: 4,
      judul: "Sosialisasi Nilai Luhur dan Etika Berorganisasi bagi Seluruh Anggota",
      created_at: "2025-04-10T13:00:00Z",
      created_at_formatted: "10 April 2025",
      isi: "Akan diselenggarakan sesi pengarahan dan pembekalan ke-SH-an yang dipimpin langsung oleh dewan pelatih dan sesepuh organisasi. Acara ini bertujuan menanamkan pemahaman etika, rasa tanggung jawab, serta penguatan karakter persaudaraan yang sejati di dalam maupun di luar lingkungan sekolah.",
      lampiran: "dokumen/01JWFT36FV2AZEV1K9JCCTARQT.pdf",
      attachments: [
        {
          id: 401,
          pengumuman_id: 4,
          label: "Materi Panduan Etika & Nilai Luhur",
          asset_type: "document",
          resource_type: "raw",
          secure_url: "dokumen/01JWFT36FV2AZEV1K9JCCTARQT.pdf",
          public_id: "psht/pengumuman/01JWFT36FV2AZEV1K9JCCTARQT",
          format: "pdf",
          mime_type: "application/pdf",
          bytes: 1448,
          sort_order: 1,
        },
      ],
    },
  ],
  extracurriculars: [
    {
      id: 1,
      nama: "Persaudaraan Setia Hati Terate (PSHT)",
      deskripsi: "Pendidikan pencak silat ajaran SH Terate yang memadukan olah fisik, teknik beladiri praktis, senam jurus, olah pernapasan rohani, serta pembentukan karakter berbudi luhur tahu benar dan salah.",
      nama_pembina: "Bambang Sudarsono, S.Pd.",
      nama_ketua: "Muhammad Rizky Pratama",
      jadwal: "Selasa & Jumat, 15.30 - 17.30 WIB",
      lokasi: "Lapangan Utama SMKN Darul Ulum Muncar",
      gambar: "ekstrakurikuler/01JVGWZ7GYCWBS8RTSD22G4SB1.jpeg",
    },
    {
      id: 2,
      nama: "Seni Bela Diri & Prestasi Tanding",
      deskripsi: "Pengembangan bakat atlet pencak silat kategori tanding dan seni tunggal/ganda/regu (TGR) untuk persiapan kompetisi O2SN, kejurkab, dan ajang prestasi pencak silat tingkat pelajar.",
      nama_pembina: "Agus Prasetyo, S.Kom.",
      nama_ketua: "Dimas Arya Wijaya",
      jadwal: "Rabu & Sabtu, 15.30 - 17.30 WIB",
      lokasi: "Aula Serbaguna SMKN Darul Ulum Muncar",
      gambar: "ekstrakurikuler/01JVKJPK3DD76355RXCDYMVG46.jpg",
    },
    {
      id: 3,
      nama: "Kepemudaan & Tanggap Sosial",
      deskripsi: "Kegiatan pembinaan kedisiplinan mental, kepedulian sosial, bakti lingkungan, serta latihan kepemimpinan organisasi siswa di lingkungan sekolah dan masyarakat.",
      nama_pembina: "Siti Rahmawati, M.Pd.",
      nama_ketua: "Ahmad Fauzi",
      jadwal: "Kamis, 15.30 - 17.00 WIB",
      lokasi: "Ruang Ekstrakurikuler & Area Terbuka Hijau",
      gambar: "ekstrakurikuler/01JVKJZT2413CCBF3EKCHDYC1N.jpg",
    },
  ],
  statistics: { siswa: 18, pelatih: 7, warga: 24, ekstrakurikuler: 3, galeri: 4 },
  source: "fallback",
};

export const fallbackGalleries = [
  {
    id: 1,
    nama_galeri: "Latihan Rutin & Olah Fisik Pencak Silat",
    deskripsi: "Dokumentasi kegiatan pembinaan teknik beladiri, olah fisik kuda-kuda, dan pembentukan karakter pesilat di SMKN Darul Ulum Muncar.",
    created_at: "2025-05-15T08:00:00Z",
    created_at_formatted: "15 Mei 2025",
    images: [
      {
        id: 101,
        gallery_id: 1,
        path: "images/01JVNSSD76PVMPKHEA6FBCYACB.jpg",
        caption: "Latihan ketahanan fisik dan pematangan gerak jurus dasar",
      },
      {
        id: 102,
        gallery_id: 1,
        path: "images/01JVNSSD7F8R1RR0Q0BJ4WATEZ.jpg",
        caption: "Pengarahan pembina dan dewan pelatih sebelum latihan bersama",
      },
      {
        id: 103,
        gallery_id: 1,
        path: "images/01JVNSZECQ5CCD8NX16SSA1VW3.jpeg",
        caption: "Latihan senam jurus massal di lapangan sekolah",
      },
      {
        id: 104,
        gallery_id: 1,
        path: "images/01JVNTDS4RGBK70YJG5AQQA0C7.jpg",
        caption: "Pendalaman materi teknik kembangan dan sambung persaudaraan",
      },
    ],
  },
  {
    id: 2,
    nama_galeri: "Ujian Kenaikan Tingkat (UKT) & Tradisi Ke-SH-an",
    deskripsi: "Momen evaluasi kenaikan tingkat sabuk dan penguatan ikatan kekeluargaan sesama warga dan siswa PSHT.",
    created_at: "2025-04-28T09:00:00Z",
    created_at_formatted: "28 April 2025",
    images: [
      {
        id: 201,
        gallery_id: 2,
        path: "images/01JVNTG59B160RYA09VTGAXNH5.jpg",
        caption: "Siswa berbaris khidmat pada prosesi pembukaan ujian kenaikan tingkat",
      },
      {
        id: 202,
        gallery_id: 2,
        path: "images/01JVNTG59M8TQX2ZD165S2DWMY.jpeg",
        caption: "Ujian ketahanan mental dan fisik siswa di hadapan para sesepuh",
      },
      {
        id: 203,
        gallery_id: 2,
        path: "images/01JVNTHV1Z1MGQ0TFYEKVYRFXT.jpg",
        caption: "Penyematan sabuk kelulusan tingkat oleh perwakilan pelatih",
      },
      {
        id: 204,
        gallery_id: 2,
        path: "images/01JVNTHV26M0Y6RPA5XXN41YK1.jpeg",
        caption: "Doa bersama dan syukuran persaudaraan setelah evaluasi materi",
      },
    ],
  },
  {
    id: 3,
    nama_galeri: "Bakti Sosial & Kepedulian Lingkungan",
    deskripsi: "Wujud nyata pengamalan falsafah Memayu Hayuning Bawana melalui kegiatan gotong royong dan silaturahmi dengan warga sekitar.",
    created_at: "2025-04-12T07:30:00Z",
    created_at_formatted: "12 April 2025",
    images: [
      {
        id: 301,
        gallery_id: 3,
        path: "images/01JWF4NYAH15542KPHNF6N9TE2.jpg",
        caption: "Aksi bersih lingkungan bersama para siswa dan warga sekolah",
      },
      {
        id: 302,
        gallery_id: 3,
        path: "images/01JWF4NYATPAF5N9DZM87M3WHN.jpg",
        caption: "Gotong royong pembersihan fasilitas umum di Dusun Krajan",
      },
      {
        id: 303,
        gallery_id: 3,
        path: "images/01JWF4NYAZJPXDZ09TGTETSFAT.jpg",
        caption: "Penyerahan santunan dan bingkisan tali asih kepada warga",
      },
      {
        id: 304,
        gallery_id: 3,
        path: "images/01JWF4TR7VVN6ECV8NRV9HP9ZY.jpg",
        caption: "Foto bersama seluruh peserta bakti sosial dan pengurus rayon",
      },
    ],
  },
];

export const fallbackPeople: Person[] = [
  // ==========================================
  // SISWA AKTIF (Total 24 siswa - 3 Halaman)
  // ==========================================
  // Halaman 1 (Persis Foto 1)
  { id: 6, nama: "Siti Nurhaliza", tipe: "siswa", jenis_kelamin: "P", alamat: "Jl. Dahlia No. 4", no_hp: "081234567804", sabuk: "Polos", foto: null },
  { id: 5, nama: "Rizky Maulana", tipe: "siswa", jenis_kelamin: "L", alamat: "Jl. Mawar No. 3", no_hp: "081234567803", sabuk: "Jambon", foto: null },
  { id: 4, nama: "Putri Aisyah", tipe: "siswa", jenis_kelamin: "P", alamat: "Jl. Anggrek No. 2", no_hp: "081234567802", sabuk: "Hijau", foto: null },
  { id: 10, nama: "Nadia Zahra", tipe: "siswa", jenis_kelamin: "P", alamat: "Jl. Cempaka No. 8", no_hp: "081234567808", sabuk: "Putih", foto: null },
  { id: 11, nama: "Bayu Pratama", tipe: "siswa", jenis_kelamin: "L", alamat: "Jl. Flamboyan No. 9", no_hp: "081234567809", sabuk: "Jambon", foto: null },
  { id: 12, nama: "Aulia Rahma", tipe: "siswa", jenis_kelamin: "P", alamat: "Jl. Bougenville No. 10", no_hp: "081234567810", sabuk: "Hijau", foto: null },
  { id: 3, nama: "Ahmad Fauzan", tipe: "siswa", jenis_kelamin: "L", alamat: "Jl. Melati No. 1", no_hp: "081234567801", sabuk: "Polos", foto: null },
  { id: 34, nama: "Aman Sentosa", tipe: "siswa", jenis_kelamin: "L", alamat: "Semarang", no_hp: "082132212312321", sabuk: "Putih", foto: null },

  // Halaman 2 (Persis Foto 2)
  { id: 1, nama: "Muhammad Ridwan", tipe: "siswa", jenis_kelamin: "L", alamat: "Yogyakarta", no_hp: "08231231312", sabuk: "Putih", foto: "foto-siswa/01JWEFWSMX302Y4Q09BEA4TJBV.jpg" },
  { id: 9, nama: "Ilham Saputra", tipe: "siswa", jenis_kelamin: "L", alamat: "Jl. Teratai No. 7", no_hp: "081234567807", sabuk: "Polos", foto: null },
  { id: 7, nama: "Fahmi Hidayat", tipe: "siswa", jenis_kelamin: "L", alamat: "Jl. Kenanga No. 5", no_hp: "081234567805", sabuk: "Jambon", foto: null },
  { id: 8, nama: "Dewi Sartika", tipe: "siswa", jenis_kelamin: "P", alamat: "Jl. Kamboja No. 6", no_hp: "081234567806", sabuk: "Hijau", foto: null },
  { id: 101, nama: "Dimas Arya Wijaya", tipe: "siswa", jenis_kelamin: "L", alamat: "Dusun Krajan, Wringinputih", no_hp: "082234567811", sabuk: "Hijau", foto: "user_photos/1738805038_1KRM_21BsYYquqGmF9ykj6Mk0jC1CorpK.jpg" },
  { id: 102, nama: "Bagas Dwi Saputra", tipe: "siswa", jenis_kelamin: "L", alamat: "Desa Kedungrejo, Muncar", no_hp: "082234567812", sabuk: "Polos", foto: null },
  { id: 103, nama: "Rian Hidayat", tipe: "siswa", jenis_kelamin: "L", alamat: "Tembokrejo, Muncar", no_hp: "082234567813", sabuk: "Jambon", foto: null },
  { id: 104, nama: "Anisa Safitri", tipe: "siswa", jenis_kelamin: "P", alamat: "Sumberberas, Muncar", no_hp: "082234567814", sabuk: "Putih", foto: null },

  // Halaman 3
  { id: 105, nama: "Fajar Prasetyo", tipe: "siswa", jenis_kelamin: "L", alamat: "Blambangan, Muncar", no_hp: "082234567815", sabuk: "Hijau", foto: null },
  { id: 106, nama: "Laila Maharani", tipe: "siswa", jenis_kelamin: "P", alamat: "Kedungringin, Muncar", no_hp: "082234567816", sabuk: "Polos", foto: null },
  { id: 107, nama: "Gilang Ramadhan", tipe: "siswa", jenis_kelamin: "L", alamat: "Dusun Krajan, Tembokrejo", no_hp: "082234567817", sabuk: "Jambon", foto: null },
  { id: 108, nama: "Dinda Kirana", tipe: "siswa", jenis_kelamin: "P", alamat: "Jl. Pelabuhan Muncar", no_hp: "082234567818", sabuk: "Putih", foto: null },
  { id: 109, nama: "Wahyu Nugroho", tipe: "siswa", jenis_kelamin: "L", alamat: "Wringinputih, Muncar", no_hp: "082234567819", sabuk: "Hijau", foto: null },
  { id: 110, nama: "Tiara Anggraini", tipe: "siswa", jenis_kelamin: "P", alamat: "Sumbersewu, Muncar", no_hp: "082234567820", sabuk: "Polos", foto: null },
  { id: 111, nama: "Hendra Setiawan", tipe: "siswa", jenis_kelamin: "L", alamat: "Kumendung, Muncar", no_hp: "082234567821", sabuk: "Jambon", foto: null },
  { id: 112, nama: "Bella Novita", tipe: "siswa", jenis_kelamin: "P", alamat: "Kedungrejo, Muncar", no_hp: "082234567822", sabuk: "Putih", foto: null },

  // ==========================================
  // PELATIH (Total 9 orang)
  // ==========================================
  { id: 13, nama: "Budi Santoso", tipe: "pelatih", jenis_kelamin: "L", alamat: "Jl. Merpati No. 11", no_hp: "081245678901", foto: null },
  { id: 14, nama: "Ratna Sari", tipe: "pelatih", jenis_kelamin: "P", alamat: "Jl. Garuda No. 12", no_hp: "081245678902", foto: null },
  { id: 15, nama: "Andi Nugroho", tipe: "pelatih", jenis_kelamin: "L", alamat: "Jl. Rajawali No. 13", no_hp: "081245678903", foto: null },
  { id: 16, nama: "Lilis Marlina", tipe: "pelatih", jenis_kelamin: "P", alamat: "Jl. Elang No. 14", no_hp: "081245678904", foto: null },
  { id: 17, nama: "Hendra Wijaya", tipe: "pelatih", jenis_kelamin: "L", alamat: "Jl. Cendrawasih No. 15", no_hp: "081245678905", foto: null },
  { id: 201, nama: "Bambang Sudarsono, S.Pd.", tipe: "pelatih", jenis_kelamin: "L", alamat: "Muncar, Banyuwangi", no_hp: "081245678900", foto: "foto-guru/01JVM6PS97PJYC4H528SMVNVX6.jpg" },
  { id: 202, nama: "Agus Prasetyo, S.Kom.", tipe: "pelatih", jenis_kelamin: "L", alamat: "Banyuwangi", no_hp: "081245678908", foto: "foto-guru/01JVM6S4B692GMMFZH2M7RMME0.png" },
  { id: 203, nama: "Mas Joko Santoso", tipe: "pelatih", jenis_kelamin: "L", alamat: "Dusun Krajan, Muncar", no_hp: "081245678906", foto: "user_photos/1738814641_Desain tanpa judul (2).png" },
  { id: 204, nama: "Mas Eko Wahyudi", tipe: "pelatih", jenis_kelamin: "L", alamat: "Wringinputih, Muncar", no_hp: "081245678907", foto: "user_photos/1746854063_3.jpeg" },

  // ==========================================
  // WARGA (Total 20 orang)
  // ==========================================
  { id: 18, nama: "Tono Subekti", tipe: "warga", jenis_kelamin: "L", alamat: "Jl. Sawo No. 1", no_hp: "081256789001", foto: null },
  { id: 19, nama: "Yuni Astuti", tipe: "warga", jenis_kelamin: "P", alamat: "Jl. Mangga No. 2", no_hp: "081256789002", foto: null },
  { id: 20, nama: "Slamet Riyadi", tipe: "warga", jenis_kelamin: "L", alamat: "Jl. Durian No. 3", no_hp: "081256789003", foto: null },
  { id: 21, nama: "Rina Marlina", tipe: "warga", jenis_kelamin: "P", alamat: "Jl. Nangka No. 4", no_hp: "081256789004", foto: null },
  { id: 22, nama: "Agus Haryanto", tipe: "warga", jenis_kelamin: "L", alamat: "Jl. Pepaya No. 5", no_hp: "081256789005", foto: null },
  { id: 23, nama: "Dewi Kusuma", tipe: "warga", jenis_kelamin: "P", alamat: "Jl. Rambutan No. 6", no_hp: "081256789006", foto: null },
  { id: 24, nama: "Eko Wibowo", tipe: "warga", jenis_kelamin: "L", alamat: "Jl. Belimbing No. 7", no_hp: "081256789007", foto: null },
  { id: 25, nama: "Maya Lestari", tipe: "warga", jenis_kelamin: "P", alamat: "Jl. Duku No. 8", no_hp: "081256789008", foto: null },
  { id: 26, nama: "Gunawan Saputra", tipe: "warga", jenis_kelamin: "L", alamat: "Jl. Pisang No. 9", no_hp: "081256789009", foto: null },
  { id: 27, nama: "Sari Apriani", tipe: "warga", jenis_kelamin: "P", alamat: "Jl. Jambu No. 10", no_hp: "081256789010", foto: null },
  { id: 28, nama: "Heri Kurniawan", tipe: "warga", jenis_kelamin: "L", alamat: "Jl. Kedondong No. 11", no_hp: "081256789011", foto: null },
  { id: 29, nama: "Anisa Ramadhani", tipe: "warga", jenis_kelamin: "P", alamat: "Jl. Manggis No. 12", no_hp: "081256789012", foto: null },
  { id: 30, nama: "Bambang Irawan", tipe: "warga", jenis_kelamin: "L", alamat: "Jl. Jeruk No. 13", no_hp: "081256789013", foto: null },
  { id: 31, nama: "Nina Anggraini", tipe: "warga", jenis_kelamin: "P", alamat: "Jl. Apel No. 14", no_hp: "081256789014", foto: null },
  { id: 32, nama: "Dedi Firmansyah", tipe: "warga", jenis_kelamin: "L", alamat: "Jl. Semangka No. 15", no_hp: "081256789015", foto: null },
  { id: 33, nama: "Fitri Handayani", tipe: "warga", jenis_kelamin: "P", alamat: "Jl. Salak No. 16", no_hp: "081256789016", foto: null },
  { id: 301, nama: "Mas Suryanto", tipe: "warga", jenis_kelamin: "L", alamat: "Wringinputih, Muncar", no_hp: "081256789017", foto: "user_photos/1746657953_Desain tanpa judul (7).png" },
  { id: 302, nama: "Mas Tri Wibowo", tipe: "warga", jenis_kelamin: "L", alamat: "Muncar, Banyuwangi", no_hp: "081256789018", foto: "user_photos/1746860721_artworks-YDQOy2Pru5CA2rhs-x1uzgA-t500x500.jpg" },
  { id: 303, nama: "Mas Heru Kurniawan", tipe: "warga", jenis_kelamin: "L", alamat: "Tembokrejo, Muncar", no_hp: "081256789019", foto: null },
  { id: 304, nama: "Mas Budi Santoso", tipe: "warga", jenis_kelamin: "L", alamat: "Kedungrejo, Muncar", no_hp: "081256789020", foto: null },
];

export const fallbackTipeDokumen: TipeDokumen[] = [
  {
    id: 1,
    nama: "Surat Izin Orang Tua",
    deskripsi:
      '<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdc5-m4a5e_CzXPESxL0wUHfpJxBHRT8sNlvp55UrMz1CUZyg/viewform?embedded=true" width="640" height="381" frameborder="0" marginheight="0" marginwidth="0">Memuat formulir...</iframe>',
    dokumen: [],
  },
  {
    id: 2,
    nama: "Lain-lain",
    deskripsi:
      "Berikut ini adalah beberapa dokumen pendukung yang bisa diunduh dan digunakan oleh para siswa dan calon siswa.",
    dokumen: [
      {
        id: 2,
        tipe_dokumen_id: 2,
        nama_dokumen: "DOKUMEN PERSYARATAN 1",
        path: "dokumen/01JWFT36FV2AZEV1K9JCCTARQT.pdf",
      },
      {
        id: 3,
        tipe_dokumen_id: 2,
        nama_dokumen: "DOKUMEN PERSYARATAN 2",
        path: "dokumen/01JWFT36G28B7SGM31CZ82KBFY.pdf",
      },
      {
        id: 4,
        tipe_dokumen_id: 2,
        nama_dokumen: "DOKUMEN PERSYARATAN 3",
        path: "dokumen/01JWFT36G5QS86ZM51QN0H5SHV.pdf",
      },
    ],
  },
];

