-- DRAFT ONLY — DO NOT APPLY WITHOUT EXPLICIT APPROVAL.
-- Based on candidate psht.sql snapshot generated 2025-05-30.
-- This migration creates schema only. It imports no data and creates no Auth users.

begin;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_role_check check (role in ('admin', 'super_admin', 'user'))
);

create table public.legacy_users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  role text not null default 'user',
  email_verified_at timestamptz,
  profile_id uuid unique references public.profiles(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint legacy_users_role_check check (role in ('admin', 'super_admin', 'user'))
);

comment on table public.legacy_users is
  'Sanitized identity bridge for legacy Laravel users. Never store Laravel password hashes or remember tokens here.';
comment on column public.legacy_users.role is
  'Canonical values: admin, super_admin, user. Import must map legacy "super admin" to "super_admin".';

create table public.artikel (
  id bigint generated by default as identity primary key,
  judul text not null,
  slug text not null unique,
  gambar text,
  isi text not null,
  excerpt text,
  legacy_user_id bigint references public.legacy_users(id) on delete restrict,
  author_id uuid references public.profiles(id) on delete set null,
  kategori text not null,
  status text not null default 'draft',
  published_at timestamptz,
  view_count bigint not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint artikel_status_check check (status in ('draft', 'published', 'archived')),
  constraint artikel_view_count_check check (view_count >= 0),
  constraint artikel_author_present check (legacy_user_id is not null or author_id is not null)
);

comment on column public.artikel.legacy_user_id is 'Original Laravel users.id; retained for lossless attribution.';
comment on column public.artikel.author_id is 'Optional application profile UUID; public.profiles.id is a 1:1 FK to auth.users.id.';

create table public.pengumuman (
  id bigint generated by default as identity primary key,
  judul text not null,
  isi text not null,
  lampiran text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.ekstrakurikuler (
  id bigint generated by default as identity primary key,
  nama text not null,
  deskripsi text,
  nama_pembina text,
  nama_ketua text,
  jadwal text,
  lokasi text,
  gambar text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.galleries (
  id bigint generated by default as identity primary key,
  nama_galeri text not null,
  deskripsi text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.images (
  id bigint generated by default as identity primary key,
  gallery_id bigint not null references public.galleries(id) on delete cascade,
  path text not null,
  caption text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.people (
  id bigint generated by default as identity primary key,
  nama text not null,
  tipe text not null,
  jenis_kelamin text,
  alamat text,
  no_hp text,
  foto text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint people_tipe_check check (tipe in ('pelatih', 'warga', 'siswa')),
  constraint people_jenis_kelamin_check check (jenis_kelamin is null or jenis_kelamin in ('L', 'P'))
);

comment on table public.people is 'Contains personal data. Anonymous access is column-limited; alamat and no_hp are not public.';

create table public.page_settings (
  id bigint generated by default as identity primary key,
  logo text,
  judul_hero text,
  deskripsi_hero text,
  gambar_hero text,
  judul_sejarah text,
  deskripsi_sejarah text,
  gambar_sejarah text,
  judul_video text,
  deskripsi_video text,
  url_video text,
  url_video2 text,
  url_video1 text,
  visi text,
  misi text,
  gambar_struktur_organisasi text,
  syarat_pendaftaran text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  gambar_hero1 text,
  gambar_hero2 text,
  gambar_hero3 text,
  gambar_sejarah1 text,
  gambar_sejarah2 text,
  gambar_sejarah3 text
);

create unique index page_settings_singleton_idx on public.page_settings ((true));

create table public.tipe_dokumen (
  id bigint generated by default as identity primary key,
  nama text not null,
  deskripsi text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.dokumen (
  id bigint generated by default as identity primary key,
  tipe_dokumen_id bigint not null references public.tipe_dokumen(id) on delete cascade,
  nama_dokumen text not null,
  path text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Indexes for observed application queries and FK lookups.
create index artikel_status_published_at_idx on public.artikel (status, published_at desc);
create index artikel_status_view_count_idx on public.artikel (status, view_count desc);
create index artikel_legacy_user_id_idx on public.artikel (legacy_user_id);
create index artikel_author_id_idx on public.artikel (author_id);
create index pengumuman_created_at_idx on public.pengumuman (created_at desc);
create index ekstrakurikuler_created_at_idx on public.ekstrakurikuler (created_at desc);
create index galleries_created_at_idx on public.galleries (created_at desc);
create index images_gallery_id_created_at_idx on public.images (gallery_id, created_at);
create index people_tipe_nama_idx on public.people (tipe, nama);
create index dokumen_tipe_dokumen_id_idx on public.dokumen (tipe_dokumen_id);

-- Keep updated_at consistent for future server-side/admin writes.
create function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.set_current_timestamp_updated_at() from public, anon, authenticated;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_current_timestamp_updated_at();
create trigger legacy_users_set_updated_at before update on public.legacy_users
for each row execute function public.set_current_timestamp_updated_at();
create trigger artikel_set_updated_at before update on public.artikel
for each row execute function public.set_current_timestamp_updated_at();
create trigger pengumuman_set_updated_at before update on public.pengumuman
for each row execute function public.set_current_timestamp_updated_at();
create trigger ekstrakurikuler_set_updated_at before update on public.ekstrakurikuler
for each row execute function public.set_current_timestamp_updated_at();
create trigger galleries_set_updated_at before update on public.galleries
for each row execute function public.set_current_timestamp_updated_at();
create trigger images_set_updated_at before update on public.images
for each row execute function public.set_current_timestamp_updated_at();
create trigger people_set_updated_at before update on public.people
for each row execute function public.set_current_timestamp_updated_at();
create trigger page_settings_set_updated_at before update on public.page_settings
for each row execute function public.set_current_timestamp_updated_at();
create trigger tipe_dokumen_set_updated_at before update on public.tipe_dokumen
for each row execute function public.set_current_timestamp_updated_at();
create trigger dokumen_set_updated_at before update on public.dokumen
for each row execute function public.set_current_timestamp_updated_at();

-- RLS is enabled before any client-facing privileges are granted.
alter table public.profiles enable row level security;
alter table public.legacy_users enable row level security;
alter table public.artikel enable row level security;
alter table public.pengumuman enable row level security;
alter table public.ekstrakurikuler enable row level security;
alter table public.galleries enable row level security;
alter table public.images enable row level security;
alter table public.people enable row level security;
alter table public.page_settings enable row level security;
alter table public.tipe_dokumen enable row level security;
alter table public.dokumen enable row level security;

-- Explicitly remove all client privileges, including write operations.
revoke all on table public.profiles from anon, authenticated;
revoke all on table public.legacy_users from anon, authenticated;
revoke all on table public.artikel from anon, authenticated;
revoke all on table public.pengumuman from anon, authenticated;
revoke all on table public.ekstrakurikuler from anon, authenticated;
revoke all on table public.galleries from anon, authenticated;
revoke all on table public.images from anon, authenticated;
revoke all on table public.people from anon, authenticated;
revoke all on table public.page_settings from anon, authenticated;
revoke all on table public.tipe_dokumen from anon, authenticated;
revoke all on table public.dokumen from anon, authenticated;

-- Public content is read-only. Profiles and legacy users remain inaccessible.
grant select on table public.artikel to anon, authenticated;
grant select on table public.pengumuman to anon, authenticated;
grant select on table public.ekstrakurikuler to anon, authenticated;
grant select on table public.galleries to anon, authenticated;
grant select on table public.images to anon, authenticated;
grant select on table public.page_settings to anon, authenticated;
grant select on table public.tipe_dokumen to anon, authenticated;
grant select on table public.dokumen to anon, authenticated;
grant select (id, nama, tipe, foto) on table public.people to anon, authenticated;

create policy artikel_public_read on public.artikel for select to anon, authenticated using (status = 'published');
create policy pengumuman_public_read on public.pengumuman for select to anon, authenticated using (true);
create policy ekstrakurikuler_public_read on public.ekstrakurikuler for select to anon, authenticated using (true);
create policy galleries_public_read on public.galleries for select to anon, authenticated using (true);
create policy images_public_read on public.images for select to anon, authenticated using (true);
create policy people_public_read on public.people for select to anon, authenticated using (true);
create policy page_settings_public_read on public.page_settings for select to anon, authenticated using (true);
create policy tipe_dokumen_public_read on public.tipe_dokumen for select to anon, authenticated using (true);
create policy dokumen_public_read on public.dokumen for select to anon, authenticated using (true);

-- No INSERT, UPDATE, or DELETE policies are intentionally defined.

commit;
