-- Migration: 0002_add_pengumuman_attachments.sql
-- Description: Creates public.pengumuman_attachments table for multi-attachment support.
-- Security: Read-only access for anon and authenticated users via RLS.

begin;

create table public.pengumuman_attachments (
  id bigint generated by default as identity primary key,
  pengumuman_id bigint not null references public.pengumuman(id) on delete cascade,
  label text not null,
  asset_type text not null,
  resource_type text not null,
  secure_url text not null,
  public_id text not null,
  asset_id text,
  mime_type text,
  format text,
  bytes bigint,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pengumuman_attachments_asset_type_check check (asset_type in ('image', 'document', 'video', 'audio', 'other')),
  constraint pengumuman_attachments_resource_type_check check (resource_type in ('image', 'video', 'raw')),
  constraint pengumuman_attachments_bytes_check check (bytes is null or bytes >= 0),
  constraint pengumuman_attachments_sort_order_check check (sort_order >= 0)
);

comment on table public.pengumuman_attachments is
  'Multi-attachment asset metadata for public announcements (images, documents, videos, audio).';

create index pengumuman_attachments_pengumuman_id_idx
  on public.pengumuman_attachments (pengumuman_id, sort_order asc);

create trigger pengumuman_attachments_set_updated_at
  before update on public.pengumuman_attachments
  for each row execute function public.set_current_timestamp_updated_at();

alter table public.pengumuman_attachments enable row level security;

revoke all on table public.pengumuman_attachments from anon, authenticated;
grant select on table public.pengumuman_attachments to anon, authenticated;

create policy pengumuman_attachments_public_read
  on public.pengumuman_attachments
  for select
  to anon, authenticated
  using (true);

-- No INSERT, UPDATE, or DELETE policies are defined. Read-only for public clients.

commit;
