-- Migration 0003: Admin RBAC, Analytics, and Write Policies for CMS
-- Allows authenticated admins and super_admins to perform CRUD on all tables.

begin;

-- 1. Site Visits (Analytics & Traffic Tracking)
create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  path text not null,
  ip_hash text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists site_visits_created_at_idx on public.site_visits (created_at desc);
create index if not exists site_visits_path_idx on public.site_visits (path);

alter table public.site_visits enable row level security;
revoke all on table public.site_visits from anon, authenticated;
grant insert on table public.site_visits to anon, authenticated;
grant select on table public.site_visits to authenticated;

create policy site_visits_public_insert on public.site_visits for insert to anon, authenticated with check (true);

-- 2. Helper functions to check admin roles
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and role in ('admin', 'super_admin')
  );
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and role = 'super_admin'
  );
$$;

grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_super_admin() to authenticated;

-- 3. Trigger to automatically create profile on new auth.users signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  has_super boolean;
begin
  select exists (select 1 from public.profiles where role = 'super_admin') into has_super;

  insert into public.profiles (id, display_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    case when not has_super then 'super_admin' else coalesce(new.raw_user_meta_data->>'role', 'admin') end
  )
  on conflict (id) do update
  set role = case when not has_super then 'super_admin' else profiles.role end;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 4. Grant full CRUD permissions to authenticated role for all content tables
grant all on table public.artikel to authenticated;
grant all on table public.pengumuman to authenticated;
grant all on table public.ekstrakurikuler to authenticated;
grant all on table public.galleries to authenticated;
grant all on table public.images to authenticated;
grant all on table public.people to authenticated;
grant all on table public.page_settings to authenticated;
grant all on table public.tipe_dokumen to authenticated;
grant all on table public.dokumen to authenticated;
grant all on table public.profiles to authenticated;

-- Grant sequence usages for tables with identity columns
grant usage, select on all sequences in schema public to authenticated;

-- 5. RLS Write Policies (Admin & Super Admin)

-- Profiles
create policy profiles_read on public.profiles for select to authenticated using (true);
create policy profiles_update_own on public.profiles for update to authenticated using (id = auth.uid() or public.is_super_admin());
create policy profiles_superadmin_all on public.profiles for all to authenticated using (public.is_super_admin());

-- Site visits read policy
create policy site_visits_admin_read on public.site_visits for select to authenticated using (public.is_admin());

-- Artikel CRUD
create policy artikel_admin_select on public.artikel for select to authenticated using (public.is_admin());
create policy artikel_admin_insert on public.artikel for insert to authenticated with check (public.is_admin());
create policy artikel_admin_update on public.artikel for update to authenticated using (public.is_admin());
create policy artikel_admin_delete on public.artikel for delete to authenticated using (public.is_admin());

-- Pengumuman CRUD
create policy pengumuman_admin_insert on public.pengumuman for insert to authenticated with check (public.is_admin());
create policy pengumuman_admin_update on public.pengumuman for update to authenticated using (public.is_admin());
create policy pengumuman_admin_delete on public.pengumuman for delete to authenticated using (public.is_admin());

-- Ekstrakurikuler CRUD
create policy ekstrakurikuler_admin_insert on public.ekstrakurikuler for insert to authenticated with check (public.is_admin());
create policy ekstrakurikuler_admin_update on public.ekstrakurikuler for update to authenticated using (public.is_admin());
create policy ekstrakurikuler_admin_delete on public.ekstrakurikuler for delete to authenticated using (public.is_admin());

-- Galleries & Images CRUD
create policy galleries_admin_insert on public.galleries for insert to authenticated with check (public.is_admin());
create policy galleries_admin_update on public.galleries for update to authenticated using (public.is_admin());
create policy galleries_admin_delete on public.galleries for delete to authenticated using (public.is_admin());

create policy images_admin_insert on public.images for insert to authenticated with check (public.is_admin());
create policy images_admin_update on public.images for update to authenticated using (public.is_admin());
create policy images_admin_delete on public.images for delete to authenticated using (public.is_admin());

-- People CRUD (Pelatih, Warga, Siswa)
create policy people_admin_select on public.people for select to authenticated using (public.is_admin());
create policy people_admin_insert on public.people for insert to authenticated with check (public.is_admin());
create policy people_admin_update on public.people for update to authenticated using (public.is_admin());
create policy people_admin_delete on public.people for delete to authenticated using (public.is_admin());

-- Page Settings CRUD
create policy page_settings_admin_insert on public.page_settings for insert to authenticated with check (public.is_admin());
create policy page_settings_admin_update on public.page_settings for update to authenticated using (public.is_admin());
create policy page_settings_admin_delete on public.page_settings for delete to authenticated using (public.is_super_admin());

-- Tipe Dokumen & Dokumen CRUD
create policy tipe_dokumen_admin_insert on public.tipe_dokumen for insert to authenticated with check (public.is_admin());
create policy tipe_dokumen_admin_update on public.tipe_dokumen for update to authenticated using (public.is_admin());
create policy tipe_dokumen_admin_delete on public.tipe_dokumen for delete to authenticated using (public.is_admin());

create policy dokumen_admin_insert on public.dokumen for insert to authenticated with check (public.is_admin());
create policy dokumen_admin_update on public.dokumen for update to authenticated using (public.is_admin());
create policy dokumen_admin_delete on public.dokumen for delete to authenticated using (public.is_admin());

commit;
