-- Migration 0004: Admin Activity Logging for Super Admin Auditing

begin;

create table if not exists public.admin_activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  user_name text not null,
  role text not null,
  action text not null,
  entity text not null,
  details text,
  created_at timestamptz not null default now()
);

create index if not exists admin_activity_logs_created_at_idx on public.admin_activity_logs (created_at desc);
create index if not exists admin_activity_logs_user_id_idx on public.admin_activity_logs (user_id);

alter table public.admin_activity_logs enable row level security;
revoke all on table public.admin_activity_logs from anon, authenticated;

-- Only authenticated users can insert logs (when performing actions)
grant insert on table public.admin_activity_logs to authenticated;
create policy admin_activity_logs_insert on public.admin_activity_logs for insert to authenticated with check (true);

-- Only super_admin can view all activity logs
grant select on table public.admin_activity_logs to authenticated;
create policy admin_activity_logs_super_admin_select on public.admin_activity_logs
  for select to authenticated
  using (public.is_super_admin());

commit;
